### ISSUE TITLE
Issue with Tamed Ocelot:  java.lang.NoSuchMethodError: 'boolean org.bukkit.entity.Ocelot.isTamed()'

### ISSUE THREAD

**Issue by Nick2bad4u** [webbukkit/dynmap-mobs#20]
13.12 18:38:13 [Server] WARN Task #256808 for dynmap-mobs v1.4 generated an exception
13.12 18:38:13 [Server] INFO java.lang.NoSuchMethodError: 'boolean org.bukkit.entity.Ocelot.isTamed()'
13.12 18:38:13 [Server] INFO at org.dynmap.mobs.DynmapMobsPlugin$MobUpdate.run(DynmapMobsPlugin.java:334) ~[?:?]
13.12 18:38:13 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-318]
13.12 18:38:13 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.4.jar:git-Paper-318]
13.12 18:38:13 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1294) ~[patched_1.16.4.jar:git-Paper-318]
13.12 18:38:13 [Server] INFO at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-318]
13.12 18:38:13 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1209) ~[patched_1.16.4.jar:git-Paper-318]
13.12 18:38:13 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997) ~[patched_1.16.4.jar:git-Paper-318]
13.12 18:38:13 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Paper-318]

**Comment by Nick2bad4u** [comment]
I am currently using Paper 318 on 1.16.4

**Comment by LightningXCE** [comment]
Seeing same issue on 1.18.1

`>.... [22:10:12 WARN]: [dynmap-mobs] Task #4837 for dynmap-mobs v1.4 generated an exception
java.lang.NoSuchMethodError: 'boolean org.bukkit.entity.Ocelot.isTamed()'
at org.dynmap.mobs.DynmapMobsPlugin$MobUpdate.run(DynmapMobsPlugin.java:334) ~[dynmap-mobs-1.4.jar:?]
at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-155]
at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.1.jar:git-Paper-155]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1547) ~[paper-1.18.1.jar:git-Paper-155]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-155]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-155]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-155]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-155]
at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by ghost** [comment]
Forks fix this, its down to Cats and the check for tamed cats, which isnt included. If you check pull requests a couple have the fixes.

**Comment by ErythroCraft** [comment]
Same!

Spigot: spigot-1.18.2-R0.1-SNAPSHOT
dynmap-mobs: 1.4

Excerpts from the latest.log file :

[16:55:25] [Server thread/WARN]: Legacy plugin dynmap-mobs v1.4 does not specify an api-version.
...
[16:55:54] [Server thread/INFO]: [dynmap-mobs] Loading dynmap-mobs v1.4
...
[16:56:18] [Server thread/INFO]: [dynmap-mobs] Enabling dynmap-mobs v1.4
[16:56:18] [Server thread/INFO]: [dynmap-mobs] initializing
[16:56:19] [Server thread/INFO]: [dynmap-mobs] Enable layer for mobs
[16:56:19] [Server thread/INFO]: [dynmap-mobs] Layer for vehicles disabled
[16:56:19] [Server thread/INFO]: [dynmap-mobs] version 1.4 is activated
...
```
[16:56:58] [Server thread/WARN]: [dynmap-mobs] Task #89 for dynmap-mobs v1.4 generated an exception
java.lang.NoSuchMethodError: 'boolean org.bukkit.entity.Ocelot.isTamed()'
	at org.dynmap.mobs.DynmapMobsPlugin$MobUpdate.run(DynmapMobsPlugin.java:334) ~[?:?]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3462-Spigot-ffceeae-2c47af0]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3462-Spigot-ffceeae-2c47af0]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1285) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3462-Spigot-ffceeae-2c47af0]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:429) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3462-Spigot-ffceeae-2c47af0]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1237) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3462-Spigot-ffceeae-2c47af0]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1047) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3462-Spigot-ffceeae-2c47af0]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3462-Spigot-ffceeae-2c47af0]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Ocelots are not tameable. There are breadable.**

https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Ocelot.html

**Comment by ghost** [comment]
> Same!
> 
> Spigot: spigot-1.18.2-R0.1-SNAPSHOT dynmap-mobs: 1.4
> 
> Excerpts from the latest.log file :
> 
> [16:55:25] [Server thread/WARN]: Legacy plugin dynmap-mobs v1.4 does not specify an api-version. ... [16:55:54] [Server thread/INFO]: [dynmap-mobs] Loading dynmap-mobs v1.4 ... [16:56:18] [Server thread/INFO]: [dynmap-mobs] Enabling dynmap-mobs v1.4 [16:56:18] [Server thread/INFO]: [dynmap-mobs] initializing [16:56:19] [Server thread/INFO]: [dynmap-mobs] Enable layer for mobs [16:56:19] [Server thread/INFO]: [dynmap-mobs] Layer for vehicles disabled [16:56:19] [Server thread/INFO]: [dynmap-mobs] version 1.4 is activated ...
> 
> ```
> [16:56:58] [Server thread/WARN]: [dynmap-mobs] Task #89 for dynmap-mobs v1.4 generated an exception
> java.lang.NoSuchMethodError: 'boolean org.bukkit.entity.Ocelot.isTamed()'
> 	at org.dynmap.mobs.DynmapMobsPlugin$MobUpdate.run(DynmapMobsPlugin.java:334) ~[?:?]
> 	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3462-Spigot-ffceeae-2c47af0]
> 	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3462-Spigot-ffceeae-2c47af0]
> 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1285) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3462-Spigot-ffceeae-2c47af0]
> 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:429) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3462-Spigot-ffceeae-2c47af0]
> 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1237) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3462-Spigot-ffceeae-2c47af0]
> 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1047) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3462-Spigot-ffceeae-2c47af0]
> 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3462-Spigot-ffceeae-2c47af0]
> 	at java.lang.Thread.run(Thread.java:833) [?:?]
> ```
> 
> **Ocelots are not tameable. There are breadable.**
> 
> https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Ocelot.html

That ocelot check is an old check which at the time related to Cats. If you check Pull requests as I said I even provided a fork updated along with others up to 1.18
